runtime: nodejs20

env_variables:
  connecturi: "mongodb+srv://johnsonlin2001:Aucklandmogel1@cluster0.3b69l.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  PLACES_API_KEY: "AIzaSyABWuX271CinKRn3VBpNj1VX1h1qrKEHyA"
  api_key: "fCWjETWnRJRgHiOjCyTyE9C9k0ymlCVK"